/**
 * Blocked words — Czech. Sources: Shutterstock list (LDNOOBW), CC BY 4.0. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const CS_WORDS: readonly string[] = [
  "buzna",
  "čumět",
  "čurák",
  "do piče",
  "do prdele",
  "dršťka",
  "držka",
  "flundra",
  "hajzl",
  "hovno",
  "chcanky",
  "chuj",
  "jebat",
  "kokot",
  "kokotina",
  "koňomrd",
  "kunda",
  "kurva",
  "mamrd",
  "mrdat",
  "mrdka",
  "mrdník",
  "oslošoust",
  "piča",
  "píčus",
  "píchat",
  "pizda",
  "prcat",
  "prdel",
  "prdelka",
  "sračka",
  "srát",
  "šoustat",
  "šulin",
  "vypíčenec",
  "zkurvit",
  "zkurvysyn",
  "zmrd",
];
