/**
 * Blocked words — Spanish. Sources: Shutterstock list (LDNOOBW), CC BY 4.0; profanity.csv (4troDev), MIT; bad-words-next (Void Resort), MIT. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const ES_WORDS: readonly string[] = [
  "bastardo",
  "Bollera",
  "cabrón",
  "Cabrón",
  "cabrón de mierda",
  "cabron*",
  "cabrón*",
  "cabronazo",
  "cagada",
  "cagado",
  "carajo",
  "chingada",
  "chingada*",
  "chingado*",
  "chingar",
  "chucha",
  "Chupada",
  "chupapol*",
  "chupapollas",
  "Chupapollas",
  "chupeton",
  "cojon",
  "cojones",
  "cojonud*",
  "Concha de tu madre",
  "coño",
  "Coño",
  "Coprofagía",
  "culeada",
  "culear",
  "culero",
  "culo",
  "Culo",
  "Fiesta de salchichas",
  "Follador",
  "follador*",
  "Follar",
  "follar*",
  "Gilipichis",
  "gilipolla*",
  "gilipollas",
  "Gilipollas",
  "guarrada",
  "Hacer una paja",
  "hija de puta",
  "Hija de puta",
  "hijaputa",
  "Hijaputa",
  "hijo de puta",
  "Hijo de puta",
  "hijoputa",
  "Hijoputa",
  "imbecil",
  "jilipolla*",
  "Jilipollas",
  "joder",
  "joto",
  "Kapullo",
  "Lameculos",
  "Macizorra",
  "mamada",
  "Mamada",
  "mamón",
  "marica",
  "Marica",
  "maricón",
  "Maricón",
  "Mariconazo",
  "me cago en Dios",
  "me cago en Dios y en la puta mar",
  "me cago en Dios y en la puta virgen",
  "me cago en la hostia",
  "me cago en la hostia puta",
  "me cago en la hostia puta virgen",
  "me cago en la leche",
  "me cago en la leche de tu puta madre",
  "me cago en la leche merengada",
  "me cago en la leche que mamaste",
  "me cago en la madre que te parió",
  "me cago en la mar",
  "me cago en la puta",
  "me cago en la puta hostia",
  "me cago en la puta hostia mar",
  "me cago en la puta leche",
  "me cago en la puta madre",
  "me cago en la puta madre que te parió",
  "me cago en la puta mar",
  "me cago en la puta mar salada",
  "me cago en la puta vida",
  "me cago en la virgen",
  "me cago en todo",
  "me cago en tu madre",
  "me cago en tu puta madre",
  "me cago en tu puta madre en vinagre",
  "me cago en tus muertos",
  "mierda",
  "Mierda",
  "mierda*",
  "panocha",
  "pedorez",
  "pelotudo",
  "pendeja",
  "pendeja*",
  "pendejada",
  "pendejadas",
  "pendejo",
  "Pendejo",
  "pendejo*",
  "pendejos",
  "Pervertido",
  "Pezón",
  "polla",
  "puta",
  "Puta",
  "putamadre",
  "puto",
  "Ramera",
  "Sexo oral",
  "soplapolas*",
  "Soplapollas",
  "Tetas grandes",
  "Tía buena",
  "tonto del culo",
  "Trio",
  "verga",
  "Verga",
  "vete a la mierda",
  "Vulva",
];
