/**
 * Blocked words — Finnish. Sources: Shutterstock list (LDNOOBW), CC BY 4.0. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const FI_WORDS: readonly string[] = [
  "alfred nussi",
  "bylsiä",
  "haahka",
  "haista paska",
  "haista vittu",
  "hatullinen",
  "hevonkuusi",
  "hevonpaska",
  "hevonperse",
  "hevonvittu",
  "hevonvitunperse",
  "hitosti",
  "huorata",
  "hässiä",
  "juosten kustu",
  "jutku",
  "jutsku",
  "kananpaska",
  "koiranpaska",
  "kuin esterin perseestä",
  "kulli",
  "kullinluikaus",
  "kuppainen",
  "kusaista",
  "kuseksia",
  "kusettaa",
  "kusi",
  "kusipää",
  "kusta",
  "kyrpiintynyt",
  "kyrpiintyä",
  "kyrpiä",
  "kyrpä",
  "kyrpänaama",
  "kyrvitys",
  "lahtari",
  "lutka",
  "molo",
  "molopää",
  "mulkero",
  "mulkku",
  "mulkvisti",
  "munapää",
  "munaton",
  "mutakuono",
  "mutiainen",
  "nainti",
  "neekeri",
  "nekru",
  "nuolla persettä",
  "nussia",
  "nussija",
  "nussinta",
  "palli",
  "pallit",
  "paneskella",
  "panettaa",
  "paska",
  "paskainen",
  "paskamainen",
  "paskanmarjat",
  "paskantaa",
  "paskapuhe",
  "paskapää",
  "paskattaa",
  "paskiainen",
  "paskoa",
  "pentele",
  "perkele",
  "perkeleesti",
  "perse",
  "perseennuolija",
  "perseet olalla",
  "persereikä",
  "perseääliö",
  "persläpi",
  "perspano",
  "persvako",
  "pilkunnussija",
  "pillu",
  "pillut",
  "pipari",
  "pyllyvako",
  "reva",
  "ripsipiirakka",
  "runkata",
  "runkkari",
  "runkkaus",
  "runkku",
  "ryssä",
  "rättipää",
  "saatanasti",
  "suklaaosasto",
  "toosa",
  "tuhkaluukku",
  "tumputtaa",
  "turpasauna",
  "tussu",
  "tussukka",
  "tussut",
  "vakipano",
  "vetää käteen",
  "viiksi",
  "vittu",
  "vittuilla",
  "vittuilu",
  "vittumainen",
  "vittuuntua",
  "vittuuntunut",
  "vitun",
  "vitusti",
  "vituttaa",
  "vitutus",
  "äpärä",
];
