/**
 * Blocked words — Hindi (Devanagari). Sources: profanity.csv (4troDev), MIT. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const HI_WORDS: readonly string[] = [
  "कमीना",
  "कमीनी",
  "कमीने",
  "कुत्ते के बच्चे",
  "गंद",
  "गांड",
  "गांडमारना",
  "गांडु",
  "गांड़ु",
  "गांडू",
  "चुटिया",
  "चूत",
  "चूतिया",
  "चोद",
  "छुट",
  "फट्टू",
  "फड़",
  "बकचोड",
  "बकचोद",
  "बकवासी",
  "बेटीचोद",
  "भड़वा",
  "भड़वे",
  "भेंचोद",
  "भैंचोड़",
  "भोसडि़के",
  "भोसड़ीके",
  "मदरचोद",
  "मादर",
  "मादरचोद",
  "माल",
  "मुँह में ले",
  "रंडी",
  "लवड़ा",
  "लावडा",
  "लावड़ा",
  "लुंड",
  "लौड़ा",
  "साला",
  "सुअर",
];
