/**
 * Blocked words — Italian. Sources: Shutterstock list (LDNOOBW), CC BY 4.0. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const IT_WORDS: readonly string[] = [
  "allupato",
  "ammucchiata",
  "anale",
  "arrapato",
  "arrusa",
  "arruso",
  "assatanato",
  "bagascia",
  "bagassa",
  "baldracca",
  "battona",
  "belino",
  "biga",
  "bocchinara",
  "bocchino",
  "bofilo",
  "boiata",
  "brinca",
  "bucaiolo",
  "budiùlo",
  "busone",
  "caciocappella",
  "cagare",
  "cagata",
  "casci",
  "cazzata",
  "cazzimma",
  "cazzo",
  "cazzone",
  "chiappa",
  "chiavare",
  "chiavata",
  "ciospo",
  "ciucciami il cazzo",
  "coglione",
  "coglioni",
  "cozza",
  "culattina",
  "culattone",
  "culo",
  "ditalino",
  "fica",
  "figa",
  "figlio di buona donna",
  "figlio di puttana",
  "figone",
  "fottere",
  "fottersi",
  "fracicone",
  "fregna",
  "frocio",
  "froscio",
  "incazzarsi",
  "incoglionirsi",
  "ingoio",
  "leccaculo",
  "lofare",
  "loffa",
  "loffare",
  "merda",
  "merdata",
  "merdoso",
  "mignotta",
  "minchia",
  "minchione",
  "mona",
  "mussa",
  "nave scuola",
  "nerchia",
  "padulo",
  "palloso",
  "patacca",
  "patonza",
  "pecorina",
  "picio",
  "pincare",
  "pinnolone",
  "pippa",
  "pippone",
  "pisciare",
  "piscio",
  "pistolotto",
  "pomiciare",
  "pompino",
  "porca madonna",
  "porca miseria",
  "porca puttana",
  "porco due",
  "porco zio",
  "potta",
  "puppami",
  "puttana",
  "recchione",
  "rincoglionire",
  "rizzarsi",
  "rompiballe",
  "rompipalle",
  "ruffiano",
  "sbattersi",
  "sborra",
  "sborrata",
  "sborrone",
  "sbrodolata",
  "scopata",
  "scorreggiare",
  "slinguare",
  "slinguata",
  "smandrappata",
  "soccia",
  "socmel",
  "sorca",
  "spompinare",
  "sticchio",
  "stronza",
  "stronzata",
  "stronzo",
  "succhiami",
  "succhione",
  "sveltina",
  "sverginare",
  "tarzanello",
  "terrone",
  "testa di cazzo",
  "tette",
  "trombare",
  "vaffanculo",
  "vangare",
  "zinne",
  "zio cantante",
  "zoccola",
];
