/**
 * Blocked words — Portuguese. Sources: Shutterstock list (LDNOOBW), CC BY 4.0; profanity.csv (4troDev), MIT. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const PT_WORDS: readonly string[] = [
  "ânus",
  "ariano",
  "balalao",
  "bicha",
  "biscate",
  "boceta",
  "boob",
  "bosta",
  "bostão",
  "braulio de borracha",
  "buceta",
  "cabrao",
  "cacete",
  "cagalhão",
  "cagão",
  "cagar",
  "cambada",
  "caralho",
  "chifrudo",
  "chochota",
  "clitoris",
  "coito",
  "colhoes",
  "cona",
  "corno",
  "cornudo",
  "cu",
  "cusão",
  "cuzão",
  "dar o rabo",
  "dum raio",
  "escroto",
  "esporra",
  "fecal",
  "filho da puta",
  "foda",
  "foda-se",
  "foder",
  "grelho",
  "heterosexual",
  "lolita",
  "merda",
  "merda na cara",
  "otário",
  "paneleiro",
  "paspalho",
  "passar um cheque",
  "peidar",
  "peludo",
  "pilantra",
  "piranha",
  "piroca",
  "pirocudo",
  "porra",
  "puta",
  "puta que pariu",
  "puta que te pariu",
  "queca",
  "sacana",
  "se foder",
  "vadia",
  "vai à merda",
  "vai tomar no cu",
  "vai-te foder",
  "vibrador",
  "xana",
  "xochota",
];
