/**
 * Blocked words — Swedish. Sources: Shutterstock list (LDNOOBW), CC BY 4.0. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const SV_WORDS: readonly string[] = [
  "arsle",
  "brutta",
  "discofitta",
  "fitta",
  "fittig",
  "jävlar",
  "knulla",
  "kuk",
  "kuksås",
  "kötthuvud",
  "köttnacke",
  "moona",
  "moonade",
  "moonar",
  "moonat",
  "mutta",
  "neger",
  "nigger",
  "olla",
  "pippa",
  "pitt",
  "prutt",
  "pök",
  "runka",
  "röv",
  "rövhål",
  "rövknulla",
  "satan",
  "skit ner dig",
  "skita",
  "skäggbiff",
  "snedfitta",
  "snefitta",
  "subba",
];
