/**
 * Blocked words — Turkish. Sources: Shutterstock list (LDNOOBW), CC BY 4.0. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const TR_WORDS: readonly string[] = [
  "amcığa",
  "amcığı",
  "amcığın",
  "amcık",
  "amcıklar",
  "amcıklara",
  "amcıklarda",
  "amcıklardan",
  "amcıkları",
  "amcıkların",
  "amcıkta",
  "amcıktan",
  "amı",
  "amlar",
  "Çingenede",
  "Çingeneden",
  "Çingeneler",
  "Çingenelerde",
  "Çingenelerden",
  "Çingenelere",
  "Çingeneleri",
  "Çingenelerin",
  "Çingenenin",
  "Çingeneye",
  "Çingeneyi",
  "göt",
  "göte",
  "götler",
  "götlerde",
  "götlerden",
  "götlere",
  "götleri",
  "götlerin",
  "götte",
  "götten",
  "götü",
  "götün",
  "götveren",
  "götverende",
  "götverenden",
  "götverene",
  "götvereni",
  "götverenin",
  "götverenler",
  "götverenlerde",
  "götverenlerden",
  "götverenlere",
  "götverenleri",
  "götverenlerin",
  "kaltağa",
  "kaltağı",
  "kaltağın",
  "kaltak",
  "kaltaklar",
  "kaltaklara",
  "kaltaklarda",
  "kaltaklardan",
  "kaltakları",
  "kaltakların",
  "kaltakta",
  "kaltaktan",
  "orospu",
  "orospuda",
  "orospudan",
  "orospular",
  "orospulara",
  "orospularda",
  "orospulardan",
  "orospuları",
  "orospuların",
  "orospunun",
  "orospuya",
  "orospuyu",
  "otuz birci",
  "otuz bircide",
  "otuz birciden",
  "otuz birciler",
  "otuz bircilerde",
  "otuz bircilerden",
  "otuz bircilere",
  "otuz bircileri",
  "otuz bircilerin",
  "otuz bircinin",
  "otuz birciye",
  "otuz birciyi",
  "saksocu",
  "saksocuda",
  "saksocudan",
  "saksocular",
  "saksoculara",
  "saksocularda",
  "saksoculardan",
  "saksocuları",
  "saksocuların",
  "saksocunun",
  "saksocuya",
  "saksocuyu",
  "sıçmak",
  "sik",
  "sike",
  "siker sikmez",
  "siki",
  "sikilir sikilmez",
  "sikin",
  "sikler",
  "siklerde",
  "siklerden",
  "siklere",
  "sikleri",
  "siklerin",
  "sikmek",
  "sikmemek",
  "sikte",
  "sikten",
  "siktir",
  "siktirir siktirmez",
  "taşağa",
  "taşağı",
  "taşağın",
  "taşak",
  "taşaklar",
  "taşaklara",
  "taşaklarda",
  "taşaklardan",
  "taşakları",
  "taşakların",
  "taşakta",
  "taşaktan",
  "yarağa",
  "yarağı",
  "yarağın",
  "yarak",
  "yaraklar",
  "yaraklara",
  "yaraklarda",
  "yaraklardan",
  "yarakları",
  "yarakların",
  "yarakta",
  "yaraktan",
];
