/**
 * Blocked words — Ukrainian. Sources: bad-words-next (Void Resort), MIT. See CREDITS.md.
 * Entries that block everyday sentences were removed (mild insults, words with an ordinary meaning, news words, identity words). Measured against everyday Tatoeba sentences, 4 Oct 2026.
 * Syntax: a plain entry is a whole word ("x*" starts a word, "*x" ends one, "*x*" is inside one); a space makes a phrase.
 */
export const UK_WORDS: readonly string[] = [
  "*дупа",
  "*дупою",
  "*дупу",
  "*кур’в*",
  "*курва*",
  "*курво*",
  "*курву*",
  "*падлюк*",
  "*підор*",
  "*пізда*",
  "*піздец*",
  "*піхач*",
  "вилупок",
  "дурко",
  "залупо*",
  "кацап*",
  "коцап*",
  "мразот*",
  "падло",
  "патороч",
  "паторочка",
  "паторочня",
  "рагуль",
  "срацею",
  "срацію",
  "срація",
  "срацька",
  "срацья",
  "срацю",
  "сраця",
  "суко",
  "трахач",
  "хохол",
];
